# Documentation: https://roots.io/trellis/docs/local-development/
# `wordpress_sites` options: https://roots.io/trellis/docs/wordpress-sites/
# Define accompanying passwords/secrets in group_vars/development/vault.yml

wordpress_sites:
  bonsai.so:
    site_hosts:
      - canonical: bonsai.test
        redirects:
          - www.bonsai.test
    local_path: ../site # path targeting local Bedrock site directory (relative to Ansible root)
    admin_email: mason@bonsai.so
    multisite:
      enabled: false
    ssl:
      enabled: false
      provider: self-signed
    cache:
      enabled: false
    xmlrpc:
      enabled: false
